export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED';
export const FETCH_CATEGORY_SUCCEEDED = 'FETCH_CATEGORY_SUCCEEDED';
export const SET_CATEGORY = 'SET_CATEGORY';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';

export const FETCH_CATEGORY_ITEM_FAILED = 'FETCH_CATEGORY_ITEM_FAILED';
export const FETCH_CATEGORY_ITEM_SUCCEEDED = 'FETCH_CATEGORY_ITEM_SUCCEEDED';
export const SET_CATEGORY_ITEM = 'SET_CATEGORY_ITEM';
export const CLEAR_CATEGORY_ITEM = 'CLEAR_CATEGORY_ITEM';
